---
abstract: "auto call setlocale when set $ENV{\"LANG\"}"
author:
  - 'Hideaki Ohno<hide.o.j55@gmail.com>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
keywords:
  - locale
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: autolocale
no_index:
  directory:
    - t
    - xt
    - inc
    - eg
provides:
  autolocale:
    file: lib/autolocale.pm
    version: 0.05
recommends:
  Variable::Magic: 0
requires:
  POSIX: 0
  perl: 5.010000
resources:
  bugtracker: https://github.com/hideo55/p5-autolocale/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hideo55/p5-autolocale.git
version: 0.05
