---
abstract: "auto call setlocale when set $ENV{\"LANG\"}"
author:
  - 'Hideaki Ohno <hide.o.j55 {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: autolocale
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Variable::Magic: 0
requires:
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hideo55/p5-autolocale.git
version: 0.01
